/-
Copyright (c) 2026 Adam Benenson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE-APACHE.
Authors: Adam Benenson
-/

import Legitimacy.Behavioral.SpectralEmbedding
import Mathlib.Tactic

/-!
# Stackelberg node-removal behavioral lineage

This module constructs a concrete behavioral lineage from a spectral
governance graph and signal. The lineage is intentionally narrow: agents make
bounded-amplitude node-removal perturbation claims, and the action budgets are
exactly the existing `govRemoved` spectral witnesses.
-/

set_option autoImplicit false

namespace Legitimacy

open Finset Matrix BigOperators

variable {n : Nat}

/-- Concrete behavioral lineage extracted from a governance graph `G` and
signal `s`. Agents are graph nodes, states are observer/target nodes, and
actions are executable single-node-removal perturbations bounded by the
corresponding spectral witness. -/
structure StackelbergBehavioralLineage (n : Nat) [NeZero n] where
  G : GovGraph ℚ n
  s : Fin n → ℚ

namespace StackelbergBehavioralLineage

variable [NeZero n] (L : StackelbergBehavioralLineage n)

/-- The exact node-removal perturbation budget for remover `k` observed at
target node `i`. -/
def perturbationBudget (k i : Fin n) : ℚ :=
  |L.G.gov L.s i - L.G.govRemoved L.s k i|

/-- An action by node `k`: choose a target node and an executable nonnegative
amplitude no larger than that node-removal perturbation budget. -/
abbrev Action (k : Fin n) : Type :=
  Σ i : Fin n, {η : ℚ // 0 ≤ η ∧ η ≤ L.perturbationBudget k i}

/-- Target node selected by an executable node-removal perturbation action. -/
def actionTarget {k : Fin n} (a : L.Action k) : Fin n :=
  a.1

/-- Amplitude selected by an executable node-removal perturbation action. -/
def actionAmplitude {k : Fin n} (a : L.Action k) : ℚ :=
  a.2.1

/-- The zero-amplitude action, used for baseline profiles. -/
def zeroAction (k : Fin n) : L.Action k :=
  ⟨k, ⟨0, by
    constructor
    · exact le_rfl
    · exact abs_nonneg _⟩⟩

/-- The all-zero baseline profile for the Stackelberg node-removal lineage. -/
def zeroProfile : ActionProfile L.Action :=
  fun k => L.zeroAction k

/-- Replace one agent action in a dependent action profile. -/
def replaceAction (base : ActionProfile L.Action)
    (k : Fin n) (action : L.Action k) : ActionProfile L.Action :=
  fun j => if h : j = k then h.symm ▸ action else base j

/-- Behavioral game generated by the Stackelberg node-removal perturbation
lineage. A utility reward is exactly the chosen executable amplitude when the
agent's target matches the current observer state; otherwise it is zero. The
governance decision permits precisely positive executable perturbations at the
queried state. -/
def toGame : BehavioralGovernanceGame where
  Agents := Fin n
  State := Fin n
  Action := L.Action
  Utility := fun k i profile =>
    if L.actionTarget (profile k) = i then
      L.actionAmplitude (profile k)
    else
      0
  Transition := fun state _profile => state
  Observation := fun _agent _state => ObservationType.Public
  GovernanceDecision := fun state profile agent =>
    if 0 < L.actionAmplitude (profile agent) ∧
        L.actionTarget (profile agent) = state then
      BinaryDecision.Permit
    else
      BinaryDecision.Deny

section SupportLemmas

variable {L}

/-- Every concrete single-removal perturbation is bounded by the graph-wide
consistency vulnerability. -/
lemma single_removal_perturbation_le_cv (k i : Fin n) :
    L.perturbationBudget k i ≤ L.G.cv L.s := by
  simpa [perturbationBudget] using L.G.perturb_le_cv L.s k i

@[simp] private lemma actionTarget_mk
    (k i : Fin n)
    (η : {η : ℚ // 0 ≤ η ∧ η ≤ L.perturbationBudget k i}) :
    L.actionTarget (k := k) ⟨i, η⟩ = i :=
  rfl

@[simp] private lemma actionAmplitude_mk
    (k i : Fin n)
    (η : {η : ℚ // 0 ≤ η ∧ η ≤ L.perturbationBudget k i}) :
    L.actionAmplitude (k := k) ⟨i, η⟩ = η.1 :=
  rfl

private lemma actionAmplitude_nonneg {k : Fin n} (action : L.Action k) :
    0 ≤ L.actionAmplitude action :=
  action.2.2.1

private lemma actionAmplitude_le_budget {k : Fin n} (action : L.Action k) :
    L.actionAmplitude action ≤ L.perturbationBudget k (L.actionTarget action) :=
  action.2.2.2

@[simp] private lemma zeroAction_target (k : Fin n) :
    L.actionTarget (L.zeroAction k) = k :=
  rfl

@[simp] private lemma zeroAction_amplitude (k : Fin n) :
    L.actionAmplitude (L.zeroAction k) = 0 :=
  rfl

@[simp] private lemma zeroProfile_apply (k : Fin n) :
    L.zeroProfile k = L.zeroAction k :=
  rfl

@[simp] private lemma replaceAction_self
    (base : ActionProfile L.Action) (k : Fin n) (action : L.Action k) :
    L.replaceAction base k action k = action := by
  simp [replaceAction]

private lemma replaceAction_of_ne
    (base : ActionProfile L.Action) {k j : Fin n} (action : L.Action k)
    (hjk : j ≠ k) :
    L.replaceAction base k action j = base j := by
  simp [replaceAction, hjk]

private lemma replaceAction_unilateral
    (base : ActionProfile L.Action) (k : Fin n) (action : L.Action k) :
    ∀ j : Fin n, j ≠ k → L.replaceAction base k action j = base j :=
  fun _ hj => L.replaceAction_of_ne base action hj

@[simp] private lemma utility_eq_amplitude_of_target
    {k i : Fin n} {profile : ActionProfile L.Action}
    (h : L.actionTarget (profile k) = i) :
    L.toGame.Utility k i profile = L.actionAmplitude (profile k) := by
  simp [toGame, h]

@[simp] private lemma utility_eq_zero_of_ne
    {k i : Fin n} {profile : ActionProfile L.Action}
    (h : L.actionTarget (profile k) ≠ i) :
    L.toGame.Utility k i profile = 0 := by
  simp [toGame, h]

@[simp] private lemma zeroProfile_utility (k i : Fin n) :
    L.toGame.Utility k i L.zeroProfile = 0 := by
  by_cases h : k = i
  · subst h
    simp [toGame, zeroProfile, zeroAction]
  · simp [toGame, zeroProfile, zeroAction, h]

/-- Positive executable perturbation actions are permitted exactly at their
selected target state. -/
@[simp] private lemma governanceDecision_positive_target
    {k i : Fin n} {action : L.Action k}
    (hpos : 0 < L.actionAmplitude action)
    (htarget : L.actionTarget action = i)
    (base : ActionProfile L.Action) :
    L.toGame.GovernanceDecision i (L.replaceAction base k action) k =
      BinaryDecision.Permit := by
  simp [toGame, hpos, htarget]

/-- Zero executable perturbations are denied by the thresholded decision rule. -/
@[simp] private lemma governanceDecision_zero_self
    (k i : Fin n) :
    L.toGame.GovernanceDecision i L.zeroProfile k = BinaryDecision.Deny := by
  simp [toGame, zeroProfile, zeroAction]

/-- Utility gain from replacing the zero action by a target-matching action is
exactly its executable perturbation amplitude. -/
private lemma utilityGain_zero_to_action
    {k i : Fin n} {action : L.Action k}
    (htarget : L.actionTarget action = i) :
    L.toGame.utilityGain k i L.zeroProfile
      (L.replaceAction L.zeroProfile k action) =
        L.actionAmplitude action := by
  simp [BehavioralGovernanceGame.utilityGain, htarget, sub_eq_add_neg]

/-- A positive `min` of two positive rational scales remains positive. -/
lemma rat_min_pos {a b : ℚ} (ha : 0 < a) (hb : 0 < b) :
    0 < min a b := by
  rw [lt_min_iff]
  exact ⟨ha, hb⟩

end SupportLemmas

section ForwardFields

variable {L}

lemma utility_nonneg (k i : Fin n) (profile : ActionProfile L.Action) :
    0 ≤ L.toGame.Utility k i profile := by
  by_cases h : L.actionTarget (profile k) = i
  · simp [toGame, h, L.actionAmplitude_nonneg (profile k)]
  · simp [toGame, h]

lemma utility_le_budget_at_state
    (k i : Fin n) (profile : ActionProfile L.Action) :
    L.toGame.Utility k i profile ≤ L.perturbationBudget k i := by
  by_cases h : L.actionTarget (profile k) = i
  · simpa [toGame, h] using L.actionAmplitude_le_budget (profile k)
  · exact le_trans (by simp [toGame, h]) (abs_nonneg _)

/-- Every profitable best-response gain in the Stackelberg node-removal
perturbation lineage is reflected by the graph's spectral perturbation
budget. This derives the corresponding `SpectralBehavioralEmbedding` field for
the concrete lineage rather than assuming it. -/
theorem perturbation_budget_reflects_best_response_gain
    {κ : ℚ} (dev : L.toGame.ProfitableDeviation κ) :
    L.G.spViolation L.s dev.gain := by
  refine ⟨(dev.agent, dev.state), ?_⟩
  have hbase_nonneg :
      0 ≤ L.toGame.Utility dev.agent dev.state dev.base :=
    L.utility_nonneg dev.agent dev.state dev.base
  have hgain_le_deviated :
      dev.gain ≤ L.toGame.Utility dev.agent dev.state dev.deviated := by
    unfold BehavioralGovernanceGame.ProfitableDeviation.gain
    unfold BehavioralGovernanceGame.utilityGain
    linarith
  have hdeviated_budget :
      L.toGame.Utility dev.agent dev.state dev.deviated ≤
        L.perturbationBudget dev.agent dev.state :=
    L.utility_le_budget_at_state dev.agent dev.state dev.deviated
  exact le_trans hgain_le_deviated hdeviated_budget

/-- Game-level thresholded decision flips in the Stackelberg node-removal
perturbation lineage match spectral perturbation witnesses at the same gain
scale. This derives the corresponding `SpectralBehavioralEmbedding` field for
the concrete lineage. -/
theorem graph_decision_matches_game
    {κ : ℚ} (dev : L.toGame.ProfitableDeviation κ)
    (_hflip :
      L.toGame.GovernanceDecision dev.state dev.deviated dev.agent ≠
        L.toGame.GovernanceDecision dev.state dev.base dev.agent) :
    L.G.spViolation L.s dev.gain :=
  L.perturbation_budget_reflects_best_response_gain dev

end ForwardFields

section ReverseFields

variable {L}

/-- Construct an executable target action from a positive rational amplitude
bounded by the Stackelberg node-removal perturbation budget. -/
def executableAction
    (k i : Fin n) (η : ℚ)
    (hη : 0 < η) (hbudget : η ≤ L.perturbationBudget k i) :
    L.Action k :=
  ⟨i, ⟨η, ⟨le_of_lt hη, hbudget⟩⟩⟩

@[simp] private lemma executableAction_target
    (k i : Fin n) (η : ℚ)
    (hη : 0 < η) (hbudget : η ≤ L.perturbationBudget k i) :
    L.actionTarget (L.executableAction k i η hη hbudget) = i :=
  rfl

@[simp] private lemma executableAction_amplitude
    (k i : Fin n) (η : ℚ)
    (hη : 0 < η) (hbudget : η ≤ L.perturbationBudget k i) :
    L.actionAmplitude (L.executableAction k i η hη hbudget) = η :=
  rfl

/-- Any positive amplitude bounded by a concrete node-removal perturbation
budget yields a profitable unilateral deviation at every capability that can
pay for that amplitude. -/
def profitableDeviationOfBudget
    {κ η : ℚ} {k i : Fin n}
    (hη : 0 < η)
    (hcapability : η ≤ κ)
    (hbudget : η ≤ L.perturbationBudget k i) :
    L.toGame.ProfitableDeviation κ where
  agent := k
  state := i
  base := L.zeroProfile
  deviated := L.replaceAction L.zeroProfile k
    (L.executableAction k i η hη hbudget)
  unilateral := L.replaceAction_unilateral L.zeroProfile k
    (L.executableAction k i η hη hbudget)
  positive_gain := by
    simpa using
      (show 0 <
        L.toGame.utilityGain k i L.zeroProfile
          (L.replaceAction L.zeroProfile k
            (L.executableAction k i η hη hbudget)) by
        rw [L.utilityGain_zero_to_action]
        · simp [executableAction, hη]
        · simp [executableAction])
  capability_feasible := by
    rw [L.utilityGain_zero_to_action]
    · simpa [executableAction] using hcapability
    · simp [executableAction]

/-- Every positive spectral vulnerability in the Stackelberg node-removal
perturbation lineage exposes a concrete profitable behavioral deviation. This
derives the corresponding reverse `SpectralBehavioralEmbedding` field for the
concrete lineage. -/
theorem spectral_vulnerability_exposes_profitable_deviation
    (_hregular : L.toGame.BestResponseDecomposedRegularity)
    {γ : ℚ} (hγ : 0 < γ) (hviol : L.G.spViolation L.s γ) :
    ∃ κ : ℚ, 0 < κ ∧
      ∃ _dev : L.toGame.ProfitableDeviation κ, True := by
  rcases hviol with ⟨p, hp⟩
  refine ⟨γ, hγ, ?_⟩
  exact ⟨L.profitableDeviationOfBudget hγ le_rfl hp, trivial⟩

/-- A spectral violation at the normalized stability threshold exposes a
capability-feasible profitable deviation in the Stackelberg node-removal
perturbation lineage. The executable amplitude is scaled by `min` so it is
both within the spectral witness and within capability `κ`. -/
theorem spectral_threshold_violation_exposes_profitable_deviation
    (_hregular : L.toGame.BestResponseDecomposedRegularity)
    {δ κ : ℚ} (hκ : 0 < κ) (hδ : 0 < δ)
    (hviol : L.G.spViolation L.s (δ / κ)) :
    ∃ _dev : L.toGame.ProfitableDeviation κ, True := by
  rcases hviol with ⟨p, hp⟩
  let η : ℚ := min (δ / κ) κ
  have hscale : 0 < δ / κ := div_pos hδ hκ
  have hη : 0 < η := rat_min_pos hscale hκ
  have hη_capability : η ≤ κ := min_le_right _ _
  have hη_budget : η ≤ L.perturbationBudget p.1 p.2 :=
    le_trans (min_le_left _ _) hp
  exact ⟨L.profitableDeviationOfBudget hη hη_capability hη_budget, trivial⟩

end ReverseFields

section EmbeddingAndRegularity

variable {L}

/-- The four `SpectralBehavioralEmbedding` fields for the Stackelberg
node-removal perturbation lineage are theorems about the constructed game. -/
def spectralBehavioralEmbedding :
    SpectralBehavioralEmbedding L.G L.s L.toGame where
  graph_decision_matches_game := fun dev hflip =>
    L.graph_decision_matches_game dev hflip
  perturbation_budget_reflects_best_response_gain := fun dev =>
    L.perturbation_budget_reflects_best_response_gain dev
  spectral_vulnerability_exposes_profitable_deviation := fun hregular {γ} hγ hviol =>
    L.spectral_vulnerability_exposes_profitable_deviation
      hregular (γ := γ) hγ hviol
  spectral_threshold_violation_exposes_profitable_deviation := fun hregular {δ κ} hκ hδ hviol =>
    L.spectral_threshold_violation_exposes_profitable_deviation
      hregular (δ := δ) (κ := κ) hκ hδ hviol

/-- Zero consistency vulnerability rules out profitable deviations in the concrete
Stackelberg node-removal perturbation lineage. -/
theorem no_profitable_deviation_of_zeroConsistencyVulnerability
    (hsp : ZeroConsistencyVulnerability L.G L.s) {κ : ℚ} :
    ¬ ∃ _dev : L.toGame.ProfitableDeviation κ, True := by
  rintro ⟨dev, _⟩
  have hviol : L.G.spViolation L.s dev.gain :=
    L.perturbation_budget_reflects_best_response_gain dev
  have hle : dev.gain ≤ L.G.cv L.s :=
    (L.G.spViolation_iff_le_cv L.s dev.gain).mp hviol
  rw [hsp] at hle
  exact not_le_of_gt dev.gain_pos hle

/-- Deprecated compatibility alias for
`no_profitable_deviation_of_zeroConsistencyVulnerability`. -/
theorem no_profitable_deviation_of_spectralStrategyproof
    (hsp : SpectralStrategyproof L.G L.s) {κ : ℚ} :
    ¬ ∃ _dev : L.toGame.ProfitableDeviation κ, True :=
  L.no_profitable_deviation_of_zeroConsistencyVulnerability hsp

/-- The gain floor used for the vacuous decomposed-regularity certificate in
the zero-CV case. It is only used after `δ > 0`; the `else`
branch makes the monotonicity audit total over all rational `δ`. -/
def strategyproofGainFloor (κ δ : ℚ) : ℚ :=
  if 0 < δ then max 0 (δ / κ) else 0

private lemma strategyproofGainFloor_lowerBound :
    BestResponseLowerBound strategyproofGainFloor := by
  intro κ δ hκ hδ
  simp [strategyproofGainFloor, hδ]

private lemma strategyproofGainFloor_monotone :
    BestResponseMonotone strategyproofGainFloor := by
  intro κ₁ κ₂ δ hκ₁ hle
  have hκ₂ : 0 < κ₂ := lt_of_lt_of_le hκ₁ hle
  by_cases hδ : 0 < δ
  · have hdiv : δ / κ₂ ≤ δ / κ₁ :=
      div_le_div_of_nonneg_left hδ.le hκ₁ hle
    have hdiv₁_nonneg : 0 ≤ δ / κ₁ := (div_nonneg hδ.le hκ₁.le)
    have hdiv₂_nonneg : 0 ≤ δ / κ₂ := (div_nonneg hδ.le hκ₂.le)
    simp [strategyproofGainFloor, hδ,
      max_eq_right hdiv₁_nonneg, max_eq_right hdiv₂_nonneg, hdiv]
  · simp [strategyproofGainFloor, hδ]

/-- In the zero-CV case the concrete lineage has a
decomposed-regular best-response certificate: witness extraction is vacuous
because no profitable deviation exists. This is the honest bounded-lineage
regularity instance; an unconditional instance would require unbounded action
amplitudes and is not asserted here. -/
def bestResponseDecompositionOfZeroConsistencyVulnerability
    (hsp : ZeroConsistencyVulnerability L.G L.s) :
    L.toGame.BestResponseDecomposition where
  gainFloor := strategyproofGainFloor
  lowerBound := strategyproofGainFloor_lowerBound
  existence := by
    intro κ δ _hκ _hδ hdev
    exact False.elim (L.no_profitable_deviation_of_zeroConsistencyVulnerability hsp hdev)
  monotone := strategyproofGainFloor_monotone

/-- Deprecated compatibility alias for
`bestResponseDecompositionOfZeroConsistencyVulnerability`. -/
def bestResponseDecompositionOfSpectralStrategyproof
    (hsp : SpectralStrategyproof L.G L.s) :
    L.toGame.BestResponseDecomposition :=
  L.bestResponseDecompositionOfZeroConsistencyVulnerability hsp

/-- Conditional decomposed regularity for the concrete Stackelberg
node-removal perturbation lineage in the zero-CV case. -/
theorem bestResponseDecomposedRegularity_of_zeroConsistencyVulnerability
    (hsp : ZeroConsistencyVulnerability L.G L.s) :
    L.toGame.BestResponseDecomposedRegularity :=
  ⟨L.bestResponseDecompositionOfZeroConsistencyVulnerability hsp⟩

/-- Deprecated compatibility alias for
`bestResponseDecomposedRegularity_of_zeroConsistencyVulnerability`. -/
theorem bestResponseDecomposedRegularity_of_spectralStrategyproof
    (hsp : SpectralStrategyproof L.G L.s) :
    L.toGame.BestResponseDecomposedRegularity :=
  L.bestResponseDecomposedRegularity_of_zeroConsistencyVulnerability hsp

/-- The constructed embedding composes with the existing one-way theorem:
zero consistency vulnerability implies game strategyproofness for the concrete
Stackelberg node-removal perturbation lineage. -/
theorem stackelberg_zero_consistency_vulnerability_implies_game_strategyproof
    (hsp : ZeroConsistencyVulnerability L.G L.s) :
    L.toGame.GameStrategyproof :=
  SpectralBehavioralEmbedding.zero_consistency_vulnerability_implies_game_strategyproof
    L.spectralBehavioralEmbedding hsp

/-- Deprecated compatibility alias for
`stackelberg_zero_consistency_vulnerability_implies_game_strategyproof`. -/
theorem stackelberg_spectral_strategyproof_implies_game_strategyproof
    (hsp : SpectralStrategyproof L.G L.s) :
    L.toGame.GameStrategyproof :=
  stackelberg_zero_consistency_vulnerability_implies_game_strategyproof hsp

/-- In the zero-CV case, the concrete lineage supplies the
regularity certificate needed to reuse the existing spectral/game
strategyproofness iff theorem. -/
theorem stackelberg_zero_consistency_vulnerability_iff_game_strategyproof
    (hsp : ZeroConsistencyVulnerability L.G L.s) :
    ZeroConsistencyVulnerability L.G L.s ↔ L.toGame.GameStrategyproof :=
  SpectralBehavioralEmbedding.zero_consistency_vulnerability_iff_game_strategyproof
    L.spectralBehavioralEmbedding
    (L.bestResponseDecomposedRegularity_of_zeroConsistencyVulnerability hsp)

/-- Deprecated compatibility alias for
`stackelberg_zero_consistency_vulnerability_iff_game_strategyproof`. -/
theorem stackelberg_spectral_strategyproof_iff_game_strategyproof
    (hsp : SpectralStrategyproof L.G L.s) :
    SpectralStrategyproof L.G L.s ↔ L.toGame.GameStrategyproof :=
  stackelberg_zero_consistency_vulnerability_iff_game_strategyproof hsp

/-- In the zero-CV case, the concrete lineage also composes
with the existing stable-equilibrium/behavioral-persistence iff theorem. -/
theorem stackelberg_spectral_stable_equilibrium_iff_behavioral_persistence
    (hsp : ZeroConsistencyVulnerability L.G L.s) (κ δ : ℚ) :
    SpectralStableEquilibrium L.G L.s δ κ ↔
      L.toGame.BehavioralPersistentEquilibrium κ δ :=
  SpectralBehavioralEmbedding.spectral_stable_equilibrium_iff_behavioral_persistence
    L.spectralBehavioralEmbedding
    (L.bestResponseDecomposedRegularity_of_zeroConsistencyVulnerability hsp) κ δ

end EmbeddingAndRegularity

end StackelbergBehavioralLineage

end Legitimacy
