/-
Copyright (c) 2026 Adam Benenson. All rights reserved.
Released under Apache 2.0 OR MIT license as described in the file LICENSE.
Authors: Adam Benenson
-/

import Legitimacy.Reflective.ProductionSelfAudit
import Legitimacy.Impossibility.PeerRelativeReachable
import Legitimacy.Impossibility.AxiomLattice

/-!
# Production self-audit versus peer-relative graph obstruction

This module records the honest boundary between the production self-audit
certificate and the peer-relative impossibility obstruction.

The two layers do not currently share a formal carrier.  The production
self-audit certificate is a predicate on an `AuditSubject`, whose executable
checks run over an `AuditGovernanceGraph` and its finite synthesized claim
corpus.  The peer-relative obstruction is a theorem over a `DecisionPipeline`
and its `GraphConsistencyP`/`GraphSolidarityP`/`GraphMonotonicityP` predicates,
which quantify over `GovernanceGraph`-style decision systems.  Without a
faithful identification from the audited subject to the obstruction graph, a
passing audit status cannot be promoted to the graph predicates below.
-/

set_option autoImplicit false

namespace Legitimacy
namespace Reflective

def emptyGovernanceGraphForAuditOrthogonality : GovernanceGraph := []

theorem emptyGovernanceGraphForAuditOrthogonality_diagnostics :
    GraphConsistencyP emptyGovernanceGraphForAuditOrthogonality ∧
      GraphSolidarityP emptyGovernanceGraphForAuditOrthogonality ∧
        GraphMonotonicityP emptyGovernanceGraphForAuditOrthogonality := by
  simp [emptyGovernanceGraphForAuditOrthogonality, GraphConsistencyP,
    GraphSolidarityP, GraphMonotonicityP, DecisionSystem.decide, graphDecide]

theorem peerGraph_auditOrthogonality_obstructs_diagnostics :
    ¬ (GraphConsistencyP peerGraph ∧ GraphSolidarityP peerGraph ∧
        GraphMonotonicityP peerGraph) := by
  intro hdiagnostics
  exact peerGraph_not_consistent
    ((graphConsistency_eq_graphConsistencyP peerGraph).mpr hdiagnostics.1)

theorem compilerAuditGraph_consistency_check_passed :
    auditCheckStatus compilerAuditGraph AuditCheck.consistency = .ok .passed := by
  native_decide

theorem compilerAuditGraph_solidarity_check_passed :
    auditCheckStatus compilerAuditGraph AuditCheck.solidarity = .ok .passed := by
  native_decide

theorem compilerAuditGraph_monotonicity_check_passed :
    auditCheckStatus compilerAuditGraph AuditCheck.monotonicity = .ok .passed := by
  native_decide

private def finiteCorpusPeerRelativeAuditGraph : AuditGovernanceGraph where
  nodes :=
    [ .binary "finite-corpus-peer"
        "finite corpus peer-relative synthetic surface"
        [ .thresholdGate "audit_signal" 1 .permit ]
        .deny
        .firstMatch
    ]
  edges := []

private def finiteCorpusPeerRelativeId
    (claimantId : AuditClaimantId) : ClaimantId :=
  if claimantId = "baseline" then 0 else 1

private def finiteCorpusPeerRelativeClaim
    (claim : AuditGovernanceClaim) : ClaimQ :=
  ⟨finiteCorpusPeerRelativeId claim.claimantId, 1, by norm_num, []⟩

private def finiteCorpusPeerRelativeDecision : BinaryDecision → AuditDecision
  | .Permit => .permit
  | .Deny => .deny

private def finiteCorpusPeerRelativeEvalNode : AuditNodeEvaluator :=
  fun _node claims => do
    validateAuditGovernanceClaims claims
    let liftedClaims := claims.map finiteCorpusPeerRelativeClaim
    claims.mapM fun claim =>
      pure
        { claimantId := claim.claimantId
          decision :=
            finiteCorpusPeerRelativeDecision
              (peerRelativeNode liftedClaims
                (finiteCorpusPeerRelativeId claim.claimantId)) }

/-- Finite-corpus subject whose executable checker sees only the synthetic
equal-strength corpus generated by `auditGraphClaims`. Its intended all-profile
comparison graph is the ordinary peer-relative graph, but there is no
representation theorem identifying the finite corpus with every `ClaimQ`
profile. -/
def finiteCorpusPeerRelativeSubject : AuditSubject where
  graph := finiteCorpusPeerRelativeAuditGraph
  evalNode := finiteCorpusPeerRelativeEvalNode

/-- The all-profile graph intentionally paired with the finite-corpus audit
subject. It is the real peer-relative graph, not a finite audit projection. -/
def finiteCorpusPeerRelativeLiftedGraph : GovernanceGraph :=
  peerGraph

theorem finiteCorpusPeerRelativeSubject_consistency_check_passed :
    auditCheckStatus finiteCorpusPeerRelativeSubject AuditCheck.consistency =
      .ok .passed := by
  native_decide

theorem finiteCorpusPeerRelativeSubject_has_finite_corpus :
    (auditGraphClaims finiteCorpusPeerRelativeSubject).length = 2 := by
  native_decide

theorem finiteCorpusPeerRelativeLiftedGraph_not_all_profile_consistent :
    ¬ GraphConsistencyP finiteCorpusPeerRelativeLiftedGraph := by
  intro hconsistent
  exact peerGraph_not_consistent
    ((graphConsistency_eq_graphConsistencyP peerGraph).mpr hconsistent)

/-- Concrete finite-corpus guardrail: the real executable audit check passes
on the subject's finite synthetic corpus, while the paired all-profile
peer-relative graph fails the real `GraphConsistencyP` predicate. This is the
missing-representation counterexample: finite-corpus success is strictly weaker
than an all-profile graph diagnostic. -/
theorem finite_corpus_pass_counterexample_to_all_profile_consistency :
    auditCheckStatus finiteCorpusPeerRelativeSubject AuditCheck.consistency =
        .ok .passed ∧
      (auditGraphClaims finiteCorpusPeerRelativeSubject).length = 2 ∧
        ¬ GraphConsistencyP finiteCorpusPeerRelativeLiftedGraph :=
  ⟨finiteCorpusPeerRelativeSubject_consistency_check_passed,
    finiteCorpusPeerRelativeSubject_has_finite_corpus,
    finiteCorpusPeerRelativeLiftedGraph_not_all_profile_consistent⟩

/-- No representation-free implication can promote a finite synthetic-corpus
consistency pass into all-profile graph consistency. The contradiction uses the
concrete witness above rather than an abstract premise standing in for the real
checker. -/
theorem no_finite_corpus_pass_implies_all_profile_consistency_without_representation :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      auditCheckStatus subject AuditCheck.consistency = .ok .passed →
        GraphConsistencyP G) := by
  intro hbridge
  exact finiteCorpusPeerRelativeLiftedGraph_not_all_profile_consistent
    (hbridge finiteCorpusPeerRelativeSubject finiteCorpusPeerRelativeLiftedGraph
      finiteCorpusPeerRelativeSubject_consistency_check_passed)

/-- The same concrete production self-audit certificate can be paired with a
diagnostically clean graph or with the peer-relative obstruction graph.  This is
the formal symptom of the missing representation/faithfulness map: the
`AuditSubject` certificate alone does not select a `GovernanceGraph`. -/
theorem production_self_audit_certificate_does_not_identify_governanceGraph :
    ProductionSelfAuditCertificateHolds compilerAuditGraph ∧
      (GraphConsistencyP emptyGovernanceGraphForAuditOrthogonality ∧
        GraphSolidarityP emptyGovernanceGraphForAuditOrthogonality ∧
          GraphMonotonicityP emptyGovernanceGraphForAuditOrthogonality) ∧
        ¬ (GraphConsistencyP peerGraph ∧ GraphSolidarityP peerGraph ∧
            GraphMonotonicityP peerGraph) :=
  ⟨compilerProductionSelfAuditCertificateHolds,
    emptyGovernanceGraphForAuditOrthogonality_diagnostics,
    peerGraph_auditOrthogonality_obstructs_diagnostics⟩

/-- No graph-identification-free theorem can turn a passing production
consistency status into the obstruction layer's graph consistency predicate. -/
theorem no_universal_audit_consistency_pass_to_graphConsistencyP_bridge :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      auditCheckStatus subject AuditCheck.consistency = .ok .passed →
        GraphConsistencyP G) := by
  intro hbridge
  obtain ⟨G, _hsolidarity, _hmonotonicity, _hstrategyproofness,
    hnot_consistent⟩ :=
    exists_non_consistent_solid_monotone_strategyproof
  exact hnot_consistent
    ((graphConsistency_eq_graphConsistencyP G).mpr
      (hbridge compilerAuditGraph G compilerAuditGraph_consistency_check_passed))

/-- No graph-identification-free theorem can turn a passing production
solidarity status into the obstruction layer's graph solidarity predicate. -/
theorem no_universal_audit_solidarity_pass_to_graphSolidarityP_bridge :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      auditCheckStatus subject AuditCheck.solidarity = .ok .passed →
        GraphSolidarityP G) := by
  intro hbridge
  obtain ⟨G, _hconsistency, _hmonotonicity, _hstrategyproofness,
    hnot_solidary⟩ :=
    exists_non_solidarity_consistent_monotone_strategyproof
  exact hnot_solidary
    ((graphSolidarity_eq_graphSolidarityP G).mpr
      (hbridge compilerAuditGraph G compilerAuditGraph_solidarity_check_passed))

/-- No graph-identification-free theorem can turn a passing production
monotonicity status into the obstruction layer's graph monotonicity predicate. -/
theorem no_universal_audit_monotonicity_pass_to_graphMonotonicityP_bridge :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      auditCheckStatus subject AuditCheck.monotonicity = .ok .passed →
        GraphMonotonicityP G) := by
  intro hbridge
  obtain ⟨G, _hconsistency, _hsolidarity, _hstrategyproofness,
    hnot_monotone⟩ :=
    exists_non_monotonicity_consistent_solid_strategyproof
  exact hnot_monotone
    ((graphMonotonicity_eq_graphMonotonicityP G).mpr
      (hbridge compilerAuditGraph G
        compilerAuditGraph_monotonicity_check_passed))

/-- Even the three requested passing statuses together do not imply the three
obstruction-layer graph diagnostics without a faithful subject-to-graph
identification. -/
theorem no_universal_audit_passes_to_graph_diagnostics_bridge :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      auditCheckStatus subject AuditCheck.consistency = .ok .passed →
        auditCheckStatus subject AuditCheck.solidarity = .ok .passed →
          auditCheckStatus subject AuditCheck.monotonicity = .ok .passed →
            GraphConsistencyP G ∧ GraphSolidarityP G ∧
              GraphMonotonicityP G) := by
  intro hbridge
  exact peerGraph_not_consistent
    ((graphConsistency_eq_graphConsistencyP peerGraph).mpr
      (hbridge compilerAuditGraph peerGraph
        compilerAuditGraph_consistency_check_passed
        compilerAuditGraph_solidarity_check_passed
        compilerAuditGraph_monotonicity_check_passed).1)

/-- Consequently, a production self-audit certificate by itself cannot be used
as a bridge to graph diagnostics for an arbitrary `GovernanceGraph`. -/
theorem no_universal_self_audit_certificate_to_graph_diagnostics_bridge :
    ¬ (∀ subject : AuditSubject, ∀ G : GovernanceGraph,
      ProductionSelfAuditCertificateHolds subject →
        GraphConsistencyP G ∧ GraphSolidarityP G ∧ GraphMonotonicityP G) := by
  intro hbridge
  exact peerGraph_not_consistent
    ((graphConsistency_eq_graphConsistencyP peerGraph).mpr
      (hbridge compilerAuditGraph peerGraph
        compilerProductionSelfAuditCertificateHolds).1)

/-- The reachable peer-relative obstruction still fires, but it remains
orthogonal to an unrelated production self-audit certificate until a faithful
graph-identification theorem connects the audited subject to this `G`. -/
theorem production_self_audit_certificate_independent_of_reachable_obstruction
    {P : Type} [DecisionPipeline P]
    (G pref : P) (node : DecisionPipeline.NodeOf P) (suffix : P)
    (hreach : ReachablePeerRelativeDecisiveStage G pref node suffix) :
    ProductionSelfAuditCertificateHolds compilerAuditGraph ∧
      ¬ (GraphConsistencyP G ∧ GraphSolidarityP G ∧ GraphMonotonicityP G) :=
  ⟨compilerProductionSelfAuditCertificateHolds,
    reachable_peer_relative_decisive_stage_obstructs_diagnostics
      G pref node suffix hreach⟩

/-- For every reachable obstruction graph, a bridge from arbitrary
subject-level certificates to that graph's diagnostics is impossible.  A real
weld would need an additional, derived representation theorem tying that
particular audited subject to that particular graph. -/
theorem no_graph_identification_free_reachable_obstruction_certificate_bridge
    {P : Type} [DecisionPipeline P]
    (G pref : P) (node : DecisionPipeline.NodeOf P) (suffix : P)
    (hreach : ReachablePeerRelativeDecisiveStage G pref node suffix) :
    ¬ (∀ subject : AuditSubject,
      ProductionSelfAuditCertificateHolds subject →
        GraphConsistencyP G ∧ GraphSolidarityP G ∧ GraphMonotonicityP G) := by
  intro hbridge
  exact reachable_peer_relative_decisive_stage_obstructs_diagnostics
    G pref node suffix hreach
    (hbridge compilerAuditGraph compilerProductionSelfAuditCertificateHolds)

end Reflective
end Legitimacy
